<template>
    <div id="day-select">
        <ul class="days">
            <!--<li class="day">Today</li>-->
            <li
                    class="day"
                    v-for="yeahDay in days"
                    v-on:click="selectDay">{{ myFormatDay(yeahDay) }}
            </li>
        </ul>
    </div>
</template>

<script>
    /*
    SERVER:
    Data generated by API server is 7 days worth of sessions (from "today").
    N.B. That is on SERVER STARTUP.
    (Not just browser reload.)

BROWSER APP:
    Here in the Day Selector, our aim is to make a widget that returns the user's choice of one Day.
    The presented options will (of course) be the same 7 days (from "today").
    N.B. This will be on BROWSER RELOAD.
    (May or may not match your SERVER STARTUP 7 days. Cheers.)
     */
    export default {
        data() {
            return {
                selectedDay: this.$moment(), // default to "today"

                // Days O' The Week!
                days: [ 0, 1, 2, 3, 4, 5, 6 ].map(num => this.$moment().add(num, 'days'))
            }
        },
        /*
         days:Array[7]
         0:"2017-09-16T13:49:53.138Z"
         1:"2017-09-17T13:49:53.139Z"
         2:"2017-09-18T13:49:53.139Z"
         3:"2017-09-19T13:49:53.139Z"
         4:"2017-09-20T13:49:53.139Z"
         5:"2017-09-21T13:49:53.140Z"
         6:"2017-09-22T13:49:53.140Z"
        */
        methods: {
            selectDay(dayClickedEvent) {
                // Q. A Moment object, n'est-ce pas?
                // A. Oui: isAMomentObject: true
                console.log('this.days[1]: ', this.days[1])

                console.log('dayClicked.target.innerText ', dayClickedEvent.target.innerText) // Tue 09/19
                // Assigns the correct Moment object from out of the 7-day array for the day clicked on (e.g. Tue 09/19)
                this.selectedDay = this.days.find((eachDay) => this.myFormatDay(eachDay) === dayClickedEvent.target.innerText)
                console.log('selectedDay (Moment object), at END of selectDay() is: ', this.selectedDay)
//                this.$myBusVueProperty.$emit('daySelectedEvent', this.selectedDay)
                this.$myBusVueProperty.$emit('daySelectedEventCallAMethod', this.selectedDay)
            },
          myFormatDay(rawDayObj) {
              if (rawDayObj.isSame(this.$moment(), 'day')) {
                  return 'Today, mate!'
              } else {
                  return rawDayObj.format('ddd MM/DD') // ('ddd DD/MM')
              }
          }
        },
        created() {
            // NOT USED:
            let daySelectorToday = this.$moment()
            console.log('NEW! daySelectorToday is: ', daySelectorToday)
            /*
      DaySelect.vue?9a66:21
      NEW! daySelectorToday is:  Moment {_isAMomentObject: true, …}
      _d: Sat Sep 16 2017 09:43:22 GMT-0400 (EDT) ...             */
        }

    }
</script>