<template>
    <div id="day-select">
        <ul class="days">
            <!--<li class="day">Today</li>-->
            <li
                    v-bind:class="{
                    day: true,
                    active: isActive(yeahDay) }"
                    v-for="yeahDay in days"
                    v-on:click="selectDay">{{ myFormatDay(yeahDay) }}
            </li>
            <!-- LESSON 113 For MOBILE... -->
            <li class="day-selector">
                <span class="dec"
                v-on:click="selectMobile('dec')"></span>
                <span class="inc"
                v-on:click="selectMobile('inc')"></span>
            </li>
        </ul>
    </div>
</template>

<script>
    /*
    SERVER:
    Data generated by API server is 7 days worth of sessions (from "today").
    N.B. That is on SERVER STARTUP.
    (Not just browser reload.)

BROWSER APP:
    Here in the Day Selector, our aim is to make a widget that returns the user's choice of one Day.
    The presented options will (of course) be the same 7 days (from "today").
    N.B. This will be on BROWSER RELOAD.
    (May or may not match your SERVER STARTUP 7 days. Cheers.)
     */
    export default {
        // props: ['selected'], // << Just to note, Instructor does this; Passed-in from Overview.vue, where it is also simply "today" from a moment() thingie, just like I have my DATA property below for same purpose. Cheers.
        // also, he deletes the DATA 'selectedDay: moment()' thing below. I am not doing that. Cheers.
        data() {
            return {
                selectedDay: this.$moment(), // default to "today"

                // Days O' The Week!
                days: [ 0, 1, 2, 3, 4, 5, 6 ].map(num => this.$moment().add(num, 'days'))
            }
        },
        /* Moment objects:
         days:Array[7]
         0:"2017-09-16T13:49:53.138Z"
         1:"2017-09-17T13:49:53.139Z"
         2:"2017-09-18T13:49:53.139Z"
         3:"2017-09-19T13:49:53.139Z"
         4:"2017-09-20T13:49:53.139Z"
         5:"2017-09-21T13:49:53.140Z"
         6:"2017-09-22T13:49:53.140Z"
        */
         methods: {
             selectMobile(which) {
                 console.log('Ye gods 01. selectMobile which: ', which) // Yep inc
               if (which === 'inc') {
                   console.log('Ye gods 02. selectMobile inside "inc" : ') // << Yep
                   if (this.selectedDay.isSame(this.days[this.days.length])) {
                       // Already on latest available day
                       // Do not increment further
                       // TODO Fix!
                   } else {
                       // Okay to increment
                       console.log('Ye gods 03. selectMobile Okay to increment : this.selectedDay._d BEFORE ', this.selectedDay._d) // YES. BEFORE  Thu Sep 21 2017
                       var dayMore =  this.selectedDay.add(1, 'days')
                       console.log('dayMore._d ', dayMore._d)
                       console.log('dayMore ', dayMore)
                       this.selectedDay = dayMore
                       console.log('THIS! sigh ', this)
                       /* Ah CRAP.
                       I (once again) have made SAME MISTAKE.
                       My assignment of 'dayMore' to "this.selectedDay" is ***NOT*** doing what I thought it was.
                       'this' here is Vue$3 {_uid:3} namely just this stupid DaySelect.vue component.
                       It is ***NOT*** getting the value assigned to
hang on
                       */
                       console.log('Ye gods 04. selectMobile Okay to increment : this.selectedDay._d AFTER ', this.selectedDay._d) // YES!  AFTER  Fri Sep 22 2017
                       // New. Instead of ".$emitting" from inside this method, let's call another one to handle that. cheers
                       this.selectDayTakesDay(dayMore)
                   }
               }  else {
                   // 'dec'
                   console.log('Ye gods 02A. selectMobile inside "dec"')
                  console.log('Ye gods 02AA. selectMobile inside "dec" : this.selectedDay._d', this.selectedDay._d)

                   if (this.selectedDay.isSame(this.days[0])) {
                       // Already on earliest available day ("today")
                       // Do not decrement further
                       console.log('OOPS. It is today. Cannot go back in time this.selectedDay ', this.selectedDay._d)
                   } else {
                       // http://momentjs.com/docs/#/manipulating/subtract/
                       var dayLess = this.selectedDay.subtract(1, 'days')
                       console.log('dayLess._d ', dayLess._d)
                       this.selectedDay = dayLess
                       // New. Instead of ".$emitting" from inside this method, let's call another one to handle that. cheers
                       this.selectDayTakesDay(dayLess)
                   }
               }
                 /* Hah. Hmm. If I'm lucky, here on the MOBILE "click" event, I can call the SAME DAMN METHOD (on the Bus), to do the Big Change (on this.selectedDate).
                  And that in turn will do the SAME DAMN THING to send that date to Vue.js magic and re-run the movie filter computed() and ALL THAT JAZZ.
                  Wish us (me) L-U-C-K.
                  Well, seems N-O-T. Hmmph.
                  */
                 // $$$  -03AMOBILE- $$$ CALL A METHOD over on: (/UTIL/MYBUS.JS)  $$$$$$$$$$$$$$$
//                 this.$myBusVueProperty.$emit('daySelectedEventCallAMethodUtilBus', this.selectedDay)
// $$$$$$$$$$$$$$$$$$$$$$$$
             },
            isActive(dayMomentObject) {
              return dayMomentObject.isSame(this.selectedDay, 'day')
            },
             selectDayTakesDay(dayItTakes) {
               // same as selectDay(event) except simplified to just take a Moment object for the day. Good luck
                 console.log('selectDayTakesDay fer chrissakes. dayItTakes._d ', dayItTakes._d)
                 // $$$  -03AB-MOBILE-TakesDay- $$$ CALL A METHOD over on: (/UTIL/MYBUS.JS)  $$$$$$$$$$$$$$$
                 this.$myBusVueProperty.$emit('daySelectedEventCallAMethodUtilBus', dayItTakes)
// $$$$$$$$$$$$$$$$$$$$$$$$
             },
            selectDay(dayClickedEvent) {
                // Q. A Moment object, n'est-ce pas?
                // A. Oui: isAMomentObject: true
                console.log('this.days[1]: ', this.days[1])

                console.log('dayClicked.target.innerText ', dayClickedEvent.target.innerText) // Tue 09/19
                // Assigns the correct Moment object from out of the 7-day array for the day clicked on (e.g. Tue 09/19)
                this.selectedDay = this.days.find((eachDay) => this.myFormatDay(eachDay) === dayClickedEvent.target.innerText)
                console.log('selectedDay (Moment object), at END of selectDay() is: ', this.selectedDay)

                /* EXPLORING 2017-09-18
                * Hmm. FAILED.
                * This did NOT get computed() filteredMovies() to re-execute.
                * sigh.
                * Why?
                * Don't (quite) know.
                * Only difference I see is this .$emit ("daySelectedEvent") is listened to by a .$on (in MovieList) that has its function logic IN-LINE.
                 * The other .$emit below ("daySelectedEventCallAMethod") is listened to by another .$on (in MovieList) that does the SAME function logic, but in a called method. WTF.
                 * They BOTH succeed in getting the MovieList DATA property ("todayForListData') to be modified, updated with the user's selected day (e.g. Thu 09/21).
                 * But ONLY ONE of them causes the computed() filteredMovies() to get re-run. (Namely, the "call a method" one.) Hmm.
                 * That Vue.js-driven "computed()" thing is watching/monitoring/listening for certain things ... What exactly are they?
                 *
                 * https://vuejs.org/v2/guide/computed.html#Basic-Example
                 * "Vue is aware that vm.reversedMessage depends on vm.message, so it will update any bindings that depend on vm.reversedMessage when vm.message changes."
                 *
                 * Okay, above is fine, but...
                 * I have a computed() property that doesn't really have any data properties, to watch, etc.
                 * Instead it has reference to a couple of functions, elsewhere, deeper down, not directly/lexically (?) right there inside the computed() property itself:
                 * - computed() { filteredMovies() { .filter(Genre).filter(Time) }}
                 * Q. So, if a data property down inside those referenced function calls changes, does computed() track THOSE ?? ??
                 *
                * */

                // "BAD" does not call a method
                // NEWS FLASH:
                // ******* NEWS FLASH. You *can* use this.
                // (Over in MovieList.vue: Anonymous function (not "in-line")
                // function() {}.bind(this)   // << who knew. put the damned .bind() right off the closing curly brace. hot damn. works.

// $$$  -01- $$$ ANONYMOUS FUNCT $$$$$$$$$$$$$$$
//                this.$myBusVueProperty.$emit('daySelectedEvent', this.selectedDay)
// $$$$$$$$$$$$$$$$$$$$$$

                // For this .$emit, the listener .$on is over on MovieList.vue
                // Why?
                // Because that is the component with the computed() filteredMovies(), that uses inputs like Genre, Time, and now this additional one of Day
                // (Actually, it already did have 'day' in it, it was just baked in that 'day' was "today". We're expanding on that. :o)
                /* WORKS. 2017-09-18 */
                // "GOOD" Calls a method

// $$$  -02- $$$ CALL A METHOD (HERE)  $$$$$$$$$$$$$$$
//                this.$myBusVueProperty.$emit('daySelectedEventCallAMethod', this.selectedDay)
// $$$$$$$$$$$$$$$$$$$$$$$$

// $$$  -03- $$$ CALL A METHOD over on: (/UTIL/MYBUS.JS)  $$$$$$$$$$$$$$$
                this.$myBusVueProperty.$emit('daySelectedEventCallAMethodUtilBus', this.selectedDay)
// $$$$$$$$$$$$$$$$$$$$$$$$

            },
          myFormatDay(rawDayObj) {
              if (rawDayObj.isSame(this.$moment(), 'day')) {
                  return 'Today, mate!'
              } else {
                  return rawDayObj.format('ddd MM/DD') // ('ddd DD/MM')
              }
          }
        },
        created() {
            // NOT USED:
            let daySelectorToday = this.$moment()
            console.log('NEW! daySelectorToday is: << Not Used! ', daySelectorToday)
            /*
      DaySelect.vue?9a66:21
      NEW! daySelectorToday is:  Moment {_isAMomentObject: true, …}
      _d: Sat Sep 16 2017 09:43:22 GMT-0400 (EDT) ...             */
        }

    }
</script>