<template>
    <div id="day-select">
        <ul class="days">
            <!--<li class="day">Today</li>-->
            <li
                    v-bind:class="{
                    day: true,
                    active: isActive(yeahDay) }"
                    v-for="yeahDay in days"
                    v-on:click="selectDay">{{ myFormatDay(yeahDay) }}
            </li>
        </ul>
    </div>
</template>

<script>
    /*
    SERVER:
    Data generated by API server is 7 days worth of sessions (from "today").
    N.B. That is on SERVER STARTUP.
    (Not just browser reload.)

BROWSER APP:
    Here in the Day Selector, our aim is to make a widget that returns the user's choice of one Day.
    The presented options will (of course) be the same 7 days (from "today").
    N.B. This will be on BROWSER RELOAD.
    (May or may not match your SERVER STARTUP 7 days. Cheers.)
     */
    export default {
        // props: ['selected'], // << Just to note, Instructor does this; also, he deletes the DATA 'selectedDay: moment()' thing below. I am not doing that. Cheers.
        data() {
            return {
                selectedDay: this.$moment(), // default to "today"

                // Days O' The Week!
                days: [ 0, 1, 2, 3, 4, 5, 6 ].map(num => this.$moment().add(num, 'days'))
            }
        },
        /*
         days:Array[7]
         0:"2017-09-16T13:49:53.138Z"
         1:"2017-09-17T13:49:53.139Z"
         2:"2017-09-18T13:49:53.139Z"
         3:"2017-09-19T13:49:53.139Z"
         4:"2017-09-20T13:49:53.139Z"
         5:"2017-09-21T13:49:53.140Z"
         6:"2017-09-22T13:49:53.140Z"
        */
         methods: {
            isActive(dayMomentObject) {
              return dayMomentObject.isSame(this.selectedDay, 'day')
            },
            selectDay(dayClickedEvent) {
                // Q. A Moment object, n'est-ce pas?
                // A. Oui: isAMomentObject: true
                console.log('this.days[1]: ', this.days[1])

                console.log('dayClicked.target.innerText ', dayClickedEvent.target.innerText) // Tue 09/19
                // Assigns the correct Moment object from out of the 7-day array for the day clicked on (e.g. Tue 09/19)
                this.selectedDay = this.days.find((eachDay) => this.myFormatDay(eachDay) === dayClickedEvent.target.innerText)
                console.log('selectedDay (Moment object), at END of selectDay() is: ', this.selectedDay)

                /* EXPLORING 2017-09-18
                * Hmm. FAILED.
                * This did NOT get computed() filteredMovies() to re-execute.
                * sigh.
                * Why?
                * Don't (quite) know.
                * Only difference I see is this .$emit ("daySelectedEvent") is listened to by a .$on (in MovieList) that has its function logic IN-LINE.
                 * The other .$emit below ("daySelectedEventCallAMethod") is listened to by another .$on (in MovieList) that does the SAME function logic, but in a called method. WTF.
                 * They BOTH succeed in getting the MovieList DATA property ("todayForListData') to be modified, updated with the user's selected day (e.g. Thu 09/21).
                 * But ONLY ONE of them causes the computed() filteredMovies() to get re-run. (Namely, the "call a method" one.) Hmm.
                 * That Vue.js-driven "computed()" thing is watching/monitoring/listening for certain things ... What exactly are they?
                 *
                 * https://vuejs.org/v2/guide/computed.html#Basic-Example
                 * "Vue is aware that vm.reversedMessage depends on vm.message, so it will update any bindings that depend on vm.reversedMessage when vm.message changes."
                 *
                 * Okay, above is fine, but...
                 * I have a computed() property that doesn't really have any data properties, to watch, etc.
                 * Instead it has reference to a couple of functions, elsewhere, deeper down, not directly/lexically (?) right there inside the computed() property itself:
                 * - computed() { filteredMovies() { .filter(Genre).filter(Time) }}
                 * Q. So, if a data property down inside those referenced function calls changes, does computed() track THOSE ?? ??
                 *
                * */

                // "BAD" does not call a method
                // NEWS FLASH:
                // ******* NEWS FLASH. You *can* use this.
                // (Over in MovieList.vue: Anonymous function (not "in-line")
                // function() {}.bind(this)   // << who knew. put the damned .bind() right off the closing curly brace. hot damn. works.

// $$$  -01- $$$ ANONYMOUS FUNCT $$$$$$$$$$$$$$$
//                this.$myBusVueProperty.$emit('daySelectedEvent', this.selectedDay)
// $$$$$$$$$$$$$$$$$$$$$$

                // For this .$emit, the listener .$on is over on MovieList.vue
                // Why?
                // Because that is the component with the computed() filteredMovies(), that uses inputs like Genre, Time, and now this additional one of Day
                // (Actually, it already did have 'day' in it, it was just baked in that 'day' was "today". We're expanding on that. :o)
                /* WORKS. 2017-09-18 */
                // "GOOD" Calls a method

// $$$  -02- $$$ CALL A METHOD (HERE)  $$$$$$$$$$$$$$$
//                this.$myBusVueProperty.$emit('daySelectedEventCallAMethod', this.selectedDay)
// $$$$$$$$$$$$$$$$$$$$$$$$

// $$$  -03- $$$ CALL A METHOD over on: (/UTIL/MYBUS.JS)  $$$$$$$$$$$$$$$
                this.$myBusVueProperty.$emit('daySelectedEventCallAMethodUtilBus', this.selectedDay)
// $$$$$$$$$$$$$$$$$$$$$$$$

            },
          myFormatDay(rawDayObj) {
              if (rawDayObj.isSame(this.$moment(), 'day')) {
                  return 'Today, mate!'
              } else {
                  return rawDayObj.format('ddd MM/DD') // ('ddd DD/MM')
              }
          }
        },
        created() {
            // NOT USED:
            let daySelectorToday = this.$moment()
            console.log('NEW! daySelectorToday is: ', daySelectorToday)
            /*
      DaySelect.vue?9a66:21
      NEW! daySelectorToday is:  Moment {_isAMomentObject: true, …}
      _d: Sat Sep 16 2017 09:43:22 GMT-0400 (EDT) ...             */
        }

    }
</script>